name: kyda
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  email_validator: ^3.0.0
  firebase: ^9.0.3
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nameLogo.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/nameLogo11.png
    - assets/images/ai_learning.png
    - assets/images/icon.png
    - assets/images/kyda_logo.png
    - assets/images/online_learning.png
    - assets/images/sub1.png
    - assets/images/sub.png
    - assets/images/video_tutorials.png
    - lib/assets/

  